// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2a5NgoT3j87R_37FWl0APn0vNvYCRvWc',
    appId: '1:3839932474:web:2ae3e46ae8c9c0dadc9d03',
    messagingSenderId: '3839932474',
    projectId: 'flutter-firebase-alura-86ee7',
    authDomain: 'flutter-firebase-alura-86ee7.firebaseapp.com',
    storageBucket: 'flutter-firebase-alura-86ee7.appspot.com',
    measurementId: 'G-Y5FMTP2Y36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3RZAuqF4oNgNZj74qb4CpuqYwXZX13s0',
    appId: '1:3839932474:android:e8006ff5b6151179dc9d03',
    messagingSenderId: '3839932474',
    projectId: 'flutter-firebase-alura-86ee7',
    storageBucket: 'flutter-firebase-alura-86ee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_GrQNR0atOjejt3fucsBRGpt6cKkODwQ',
    appId: '1:3839932474:ios:569b5c56b242bdb7dc9d03',
    messagingSenderId: '3839932474',
    projectId: 'flutter-firebase-alura-86ee7',
    storageBucket: 'flutter-firebase-alura-86ee7.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAlura',
  );

}