CREATE TABLE VENDAS(
    NUMERO_VENDA INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    PRODUTO_ID INT NOT NULL,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    REGIAO_ID INT NOT NULL,
    NOME_REGIAO VARCHAR(50) NOT NULL,
    QTD_VENDIDA INT NOT NULL 
);