// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEI0bzQgs9e9rFF6w2SFKtajW-s9ab6Bc',
    appId: '1:272753367897:web:42153b51e432ceb0634a48',
    messagingSenderId: '272753367897',
    projectId: 'flutter-firebase-alura-e980f',
    authDomain: 'flutter-firebase-alura-e980f.firebaseapp.com',
    storageBucket: 'flutter-firebase-alura-e980f.appspot.com',
    measurementId: 'G-RQB4N200NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJakoG3Gtwzz02Mi-Hb34BdIufNFi6d4',
    appId: '1:272753367897:android:c3094a405f36039b634a48',
    messagingSenderId: '272753367897',
    projectId: 'flutter-firebase-alura-e980f',
    storageBucket: 'flutter-firebase-alura-e980f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaa5Ckh_pW61GkGiYiezkQdjDU51f-T_Y',
    appId: '1:272753367897:ios:6b9df18f5b0e1816634a48',
    messagingSenderId: '272753367897',
    projectId: 'flutter-firebase-alura-e980f',
    storageBucket: 'flutter-firebase-alura-e980f.appspot.com',
    iosBundleId: 'com.example.flutterCreateVscode',
  );

}